import type { Theme } from '@/types/canvas'

export const BUILTIN_THEMES: Theme[] = [
  {
    id: 'default',
    name: '默认',
    thumbnail: '',
    config: {},
  },
  {
    id: 'night',
    name: '星空夜景',
    thumbnail: '',
    config: {
      background: {
        type: 'gradient',
        solidColor: '#0f172aff',
        gradient: { start: '#0f172aff', end: '#1e1b4bff', direction: 'to-bottom' },
        imageUrl: '',
        imageFit: 'cover',
        opacity: 100,
      },
      textLayers: [
        {
          id: '',
          label: '标题',
          text: '星空下的故事',
          font: 'Maple Mono CN',
          bold: true,
          italic: false,
          fontSize: 120,
          color: '#e2e8f0ff',
          opacity: 100,
          letterSpacing: 4,
          rotate: 0,
          shadowDepth: 3,
          x: 50,
          y: 40,
        },
        {
          id: '',
          label: '副标题',
          text: '探索无限可能',
          font: 'Maple Mono CN',
          bold: false,
          italic: true,
          fontSize: 48,
          color: '#94a3b8ff',
          opacity: 80,
          letterSpacing: 2,
          rotate: 0,
          shadowDepth: 0,
          x: 50,
          y: 70,
        },
      ],
      watermark: {
        text: '@yezihack-cover-Craft',
        font: 'Inter',
        bold: false,
        italic: false,
        uppercase: false,
        fontSize: 16,
        opacity: 40,
        color: '#ffffff',
        x: 95,
        y: 95,
      },
    },
  },
  {
    id: 'minimal',
    name: '极简白',
    thumbnail: '',
    config: {
      background: {
        type: 'solid',
        solidColor: '#f8fafcff',
        gradient: { start: '#ffffffff', end: '#ffffffff', direction: 'to-bottom' },
        imageUrl: '',
        imageFit: 'cover',
        opacity: 100,
      },
      textLayers: [
        {
          id: '',
          label: '标题',
          text: 'MINIMAL',
          font: 'Inter',
          bold: true,
          italic: false,
          fontSize: 160,
          color: '#0f172aff',
          opacity: 100,
          letterSpacing: 12,
          rotate: 0,
          shadowDepth: 0,
          x: 50,
          y: 50,
        },
      ],
    },
  },
]
